version: '3.9'
x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics
services:
  SaaSBuilder:
    image: ghcr.io/omnistrate/saasbuilder:latest
    ports:
      - '8080:8080'
    environment:
      - PROVIDER_EMAIL=$var.providerEmail
      - PROVIDER_PASSWORD=$var.providerPassword
      - YOUR_SAAS_DOMAIN_URL=$sys.network.externalClusterEndpoint
      - MAIL_SMTP_HOST=$var.smtpHost
      - MAIL_SMTP_PORT=$var.smtpPort
      - MAIL_USER_EMAIL=$var.senderEmail
      - MAIL_USER_PASSWORD=$var.senderPassword
      - MAIL_FROM=$var.senderFrom
      - GOOGLE_ANALYTICS_TAG_ID=$var.googleAnalyticsTagID
      - GOOGLE_RECAPTCHA_SITE_KEY=$var.googleReCaptchaSiteKey
      - GOOGLE_RECAPTCHA_SECRET_KEY=$var.googleReCaptchaSecretKey
    x-omnistrate-compute:
      instanceTypes:
        - cloudProvider: aws
          apiParam: instanceType
        - cloudProvider: gcp
          apiParam: instanceType
    x-omnistrate-capabilities:
      httpReverseProxy:
        targetPort: 8080
      enableMultiZone: true
      autoscaling:
        maxReplicas: 10
        minReplicas: 2
        idleMinutesBeforeScalingDown: 2
        idleThreshold: 20
        overUtilizedMinutesBeforeScalingUp: 3
        overUtilizedThreshold: 80
    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type
        name: Instance Type
        type: String
        modifiable: true
        required: true
        export: true
      - key: providerEmail
        description: Service provider Omnistrate email address
        name: Omnistrate email
        type: String
        modifiable: true
        required: true
        export: true
      - key: providerPassword
        description: Service provider Omnistrate account password
        name: Omnistrate password
        type: String
        modifiable: true
        required: true
        export: false
      - key: smtpHost
        description: The SMTP host to be used for sending emails
        name: SMTP Host
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: smtp.gmail.com
      - key: smtpPort
        description: The SMTP port to connect to
        name: SMTP Port
        type: String
        modifiable: true
        required: false
        export: true  
        defaultValue: '587'
      - key: senderEmail
        description: email address to login to the SMTS provider
        name: SMTS email address
        type: String
        modifiable: true
        required: true
        export: true
      - key: senderPassword
        description: Password to authorize against the SMTS provider
        name: SMTS password
        type: String
        modifiable: true
        required: true
        export: false
      - key: senderFrom
        description: Add a separate From email address if different from Sender email address, otherwise leave blank
        name: From Email address
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: From Email address        
      - key: googleAnalyticsTagID
        description: Add Google Analytics tag ID, leave blank if you dont have any
        name: Google Analytics tag ID
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: Google Analytics tag ID
      - key: googleReCaptchaSiteKey
        description: Add Google reCAPTCHA(v2 Invisible) Site Key, leave blank if you dont have any
        name: Google reCAPTCHA Site Key
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: DISABLED
      - key: googleReCaptchaSecretKey
        description: Add Google reCAPTCHA(v2 Invisible) Secret Key, leave blank if you dont have any
        name: Google reCAPTCHA Secret Key
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: DISABLED